controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

# Basic controllers
app_login:
    path: /login
    controller: App\Controller\LoginController::index

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_verify_email:
    path: //verify/email
    controller: App\Controller\RegistrationController::verifyUserEmail

app_category:
    path: /category
    controller: App\Controller\CategoryController::index

category_form:
    path: /category/edit
    controller: App\Controller\CategoryController::insert

category_form_edit:
    path: /category/edit/{id}
    controller: App\Controller\CategoryController::edit

app_expense:
    path: /expense
    controller: App\Controller\ExpenseController::index

expense_form:
    path: /expense/edit
    controller: App\Controller\ExpenseController::insert

expense_form_edit:
    path: /expense/edit/{id}
    controller: App\Controller\ExpenseController::edit

# Api controllers
api_category_create:
    path: /api/category
    controller: App\Controller\Api\CategoryController::create
    methods: POST|HEAD

api_category_get:
    path: /api/category/{id}
    controller: App\Controller\Api\CategoryController::get
    methods: GET|HEAD
    requirements:
        page: '\d+'

api_category_update:
    path: /api/category/{id}
    controller: App\Controller\Api\CategoryController::update
    methods: PUT|HEAD
    requirements:
        page: '\d+'

api_category_delete:
    path: /api/category/{id}
    controller: App\Controller\Api\CategoryController::delete
    methods: DELETE|HEAD
    requirements:
        page: '\d+'

api_category_search:
    path: /categories
    controller: App\Controller\Api\CategoryController::search
    methods: GET|HEAD

api_expense_create:
    path: /api/expense
    controller: App\Controller\Api\ExpenseController::create
    methods: POST|HEAD

api_expense_get:
    path: /api/expense/{id}
    controller: App\Controller\Api\ExpenseController::get
    methods: GET|HEAD
    requirements:
        page: '\d+'

api_expense_update:
    path: /api/expense/{id}
    controller: App\Controller\Api\ExpenseController::update
    methods: PUT|HEAD
    requirements:
        page: '\d+'

api_expense_delete:
    path: /api/expense/{id}
    controller: App\Controller\Api\ExpenseController::delete
    methods: DELETE|HEAD
    requirements:
        page: '\d+'

api_expense_search:
    path: /api/expense
    controller: App\Controller\Api\ExpenseController::search
    methods: GET|HEAD

api_expense_aggregate_by_date:
    path: /api/aggregateByDate
    controller: App\Controller\Api\ExpenseController::aggregateByDate
    methods: GET|HEAD

